language: ruby
cache: bundler
sudo: false
bundler_args: --without debug
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
jdk:
  - oraclejdk8
rvm:
  - 2.1
  - 2.2
  - jruby-head
matrix:
  allow_failures:
      - rvm: jruby-head
jdk:
  - oraclejdk8