language: ruby
cache: bundler
sudo: false
bundler_args: --without debug
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
jdk:
  - oraclejdk8
rvm:
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - jruby-head
matrix:
  allow_failures:
      - rvm: jruby-head
before_install:
  - gem update --system
